-- Crear tabla USUARIO
CREATE TABLE USUARIO (
    IDUSU  INTEGER NOT NULL,
    NOMUSU VARCHAR2(50),
    PWUSU VARCHAR2(15),
    NIVUSU INTEGER
);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( IDUSU );
-- Crear secuencia incrementable USUARIO
CREATE SEQUENCE incrementarUSU
START WITH 1
INCREMENT BY 1;
-- Crear disparador incrementable en la tabla USUARIO
CREATE TRIGGER IDUSU
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
SELECT incrementarUSU.NEXTVAL INTO :NEW.IDUSU FROM DUAL;
END;
/

SELECT * FROM USUARIO;
-- Insertar registros en la tabla USUARIO
INSERT INTO USUARIO (NOMUSU, PWUSU, NIVUSU) VALUES ('ADMINISTRADOR', '123', '1');
INSERT INTO USUARIO (NOMUSU, PWUSU, NIVUSU) VALUES ('PERSONAL', '123', '2');

SELECT * FROM PROVEEDOR;
-- Crear tabla PROVEEDOR
CREATE TABLE PROVEEDOR (
    IDPROV   INTEGER NOT NULL,
    NOMPROV  VARCHAR2(30) NOT NULL,
    RUCPROV  CHAR(11) NOT NULL,
    TELPROV CHAR(9),
    EMAPROV  VARCHAR2(30),
    TIPPROV  VARCHAR2(18) NOT NULL,
    NCOMPROV VARCHAR2(80),
    ABREPROV VARCHAR2(8),
    DIRPROV  VARCHAR2(250) NOT NULL,
    IDUBI    CHAR(6),
    ESTPROV  CHAR(1) NOT NULL
);

ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY ( IDPROV );


-- Crear secuencia incrementable PROVEEDOR
CREATE SEQUENCE incrementarPROV
START WITH 1
INCREMENT BY 1;


-- Crear disparador incrementable en la tabla PROVEEDOR
CREATE TRIGGER IDPROV
BEFORE INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
SELECT incrementarPROV.NEXTVAL INTO :NEW.IDPROV FROM DUAL;
END;
/



-- Insertar registros en la tabla PROVEEDOR
INSERT INTO PROVEEDOR (NOMPROV, RUCPROV, TELPROV, EMAPROV, TIPPROV, NCOMPROV, ABREPROV, DIRPROV, IDUBI, ESTPROV)
VALUES ('ALFARO S.A.C.', '20108983583', '994756342', 'alfaro@hotmail.com', 'DISTRIBUIDOR', 'ALFARO', 'ALF', 'A.V SAN PABLO', '150301', 'A');
INSERT INTO PROVEEDOR (NOMPROV, RUCPROV, TELPROV, EMAPROV, TIPPROV, NCOMPROV, ABREPROV, DIRPROV, IDUBI, ESTPROV)
VALUES ('ABBOTT LABORATORIES, S.A.', '20105556783', '967446342', 'abbott@hotmail.com',  'DISTRIBUIDOR', 'ABBOTT', 'ABOT', 'A.V SIEMPRE VIVA', '150502', 'A');




--listar vista proveedor

CREATE VIEW vListarv3
AS
SELECT
	P.IDPROV,
	P.NOMPROV,
	P.RUCPROV,
	P.TELPROV,
	P.EMAPROV,
	p.TIPPROV,
	P.NCOMPROV,
	P.ABREPROV,
	P.DIRPROV,
	P.ESTPROV,
	ROW_NUMBER() OVER (ORDER BY P.IDPROV DESC) AS ORDEN
FROM PROVEEDOR P
WHERE 
	ESTPROV = 'A';

drop view "ENCRIPTACION"."VLISTARV3";
SELECT * FROM vListarv3;
SELECT * FROM UBIGEO;
SELECT * FROM proveedor;
-- Crear tabla UBIGEO
CREATE TABLE UBIGEO (
    IDUBI  CHAR(6) NOT NULL,
    DEPUBI VARCHAR2(80) NOT NULL,
    PROUBI VARCHAR2(80) NOT NULL,
    DISUBI VARCHAR2(80) NOT NULL
);
ALTER TABLE UBIGEO ADD CONSTRAINT UBIGEO_PK PRIMARY KEY ( IDUBI );


-- Relacionando la tabla UBIGEO con la tabla PROVEEDOR
ALTER TABLE PROVEEDOR
    ADD CONSTRAINT FK_UBIGEO_PROVEEDOR FOREIGN KEY (IDUBI)
        REFERENCES UBIGEO (IDUBI);


-- Insetar registros en la tabla UBIGEO
INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150101','LIMA','LIMA','LIMA');
INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150102','LIMA','LIMA','ANCON');
INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150103','LIMA','LIMA','ATE');
INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150104','LIMA','LIMA','BARRANCO');
INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150105','LIMA','LIMA','BREÑA');

INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150301','LIMA','CAJATAMBO','CAJATAMBO');
INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150302','LIMA','CAJATAMBO','COPA');

INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150501','LIMA','CAÑETE','SAN VICENTE DE CAÑETE');
INSERT INTO UBIGEO (IDUBI, DEPUBI, PROUBI, DISUBI) VALUES ('150502','LIMA','CAÑETE','ASIA');